version: '3.8'

services:
  app:
    build: .
    container_name: sumiya-app
    restart: unless-stopped
    volumes:
      - ./app:/app/app
      - ./media:/app/media
      - ./static:/app/static
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/sumiya
      - SECRET_KEY=your-secret-key
      - ENVIRONMENT=production
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sumiya-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  db:
    image: postgres:13-alpine
    container_name: sumiya-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sumiya
    networks:
      - sumiya-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  nginx:
    image: nginx:alpine
    container_name: sumiya-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      app:
        condition: service_healthy
    networks:
      - sumiya-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M

volumes:
  postgres_data:
    driver: local

networks:
  sumiya-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16 